import { FormEvent, ReactNode, useEffect, useState } from 'react'

type IconName = 'leaf'|'shield'|'sprout'|'phone'|'call'|'users'|'drop'|'chart'|'camera'|'support'|'arrow'|'menu'|'close'|'check'|'map'
const iconPaths: Record<IconName, ReactNode> = {
  leaf:<><path d="M20 3C11 3 6 7 6 13c0 3 2 5 5 5 7 0 9-9 9-15Z"/><path d="M4 21c3-7 7-10 13-14"/></>,
  shield:<><path d="m12 3 8 3v6c0 5-3 8-8 10-5-2-8-5-8-10V6l8-3Z"/><path d="m8 12 3 3 5-6"/></>,
  sprout:<><path d="M12 22V9"/><path d="M12 13C7 13 4 10 4 5c5 0 8 3 8 8ZM12 17c5 0 8-3 8-8-5 0-8 3-8 8Z"/></>,
  phone:<><rect x="6" y="2" width="12" height="20" rx="2"/><path d="M10 5h4M11 18h2"/></>,
  call:<path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.8a2 2 0 0 1-.5 2.1L8.1 9.9a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.5c.9.3 1.8.6 2.8.7a2 2 0 0 1 1.7 2.1Z"/>,
  users:<><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2"/><path d="M3 20c0-4 2-6 6-6s6 2 6 6M15 15c4 0 6 2 6 5"/></>,
  drop:<path d="M12 2S5 10 5 15a7 7 0 0 0 14 0c0-5-7-13-7-13Z"/>,
  chart:<><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></>,
  camera:<><rect x="3" y="6" width="18" height="14" rx="2"/><circle cx="12" cy="13" r="4"/><path d="m8 6 2-3h4l2 3"/></>,
  support:<><circle cx="12" cy="12" r="9"/><path d="M8 15c1 2 7 2 8 0M8 10h.01M16 10h.01"/></>,
  arrow:<><path d="M4 12h15M14 7l5 5-5 5"/></>, menu:<path d="M4 7h16M4 12h16M4 17h16"/>, close:<path d="m5 5 14 14M19 5 5 19"/>, check:<path d="m5 12 4 4L19 6"/>,
  map:<><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Z"/><path d="M9 3v15M15 6v15"/></>
}
function Icon({name,size=21}:{name:IconName,size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{iconPaths[name]}</svg>}

const nav=[['Home','/'],['About Us','/about'],['Projects','/projects'],['Mahogany Life','/farm-life'],['Guides','/guides'],['Blog','/blog']] as const
const menuPages=[['About Us','/about'],['Projects','/projects'],['Mahogany Life','/farm-life'],['Why Farmland','/why-farmland'],['Why Mahogany','/why-mahogany'],['How It Works','/how-it-works'],['Farming Guides','/guides'],['Blogs','/blog'],['Careers','/careers']] as const
const features=[['shield','Hassle-free ownership','Clear documentation and dedicated guidance.'],['sprout','Mahogany specialists','Focused plantation care through every stage.'],['phone','MyFarm technology','Updates, reports and photos in your pocket.'],['users','Co-farmer community','A community growing something meaningful.']] as const
const projects=[
  {name:'Aranya Mahogany',place:'Kanakapura Road, Bengaluru',size:'¼ acre plots',acres:'25 acres',image:'/images/project-aranya.png',tag:'Now planting'},
  {name:'Nisarga Woods',place:'Near Chikkaballapur',size:'½ acre plots',acres:'40 acres',image:'/images/project-nisarga.png',tag:'Featured'},
  {name:'Vana Legacy',place:'Mysuru Road, Bengaluru',size:'1 acre plots',acres:'32 acres',image:'/images/project-vana.png',tag:'New launch'}
]
const faqs=[['What is managed Mahogany farmland?','You own farmland dedicated to a Mahogany plantation, while a professional team coordinates planting, irrigation, maintenance, security and progress reporting.'],['Why choose Mahogany?','Mahogany is a long-lived tropical hardwood tree known for its strong form and broad crown. It suits owners who value patient, long-term stewardship.'],['Do I own the land?','Ownership structure and documents must be reviewed project by project. Always complete independent legal due diligence before purchase.'],['Can I visit before deciding?','Yes. A guided visit is the best way to understand the land, water plan, plantation design and documentation.'],['Are returns guaranteed?','No. Tree growth, timber value and land appreciation depend on many variables. No financial outcome should be treated as guaranteed.']]

function Logo({go}:{go:(p:string)=>void}){return <button className="logo" onClick={()=>go('/')} aria-label="Mahogany Farms home"><Icon name="leaf" size={31}/><span>MAHOGANY<small>FARMS</small></span></button>}
function Header({go,path}:{go:(p:string)=>void,path:string}){const [open,setOpen]=useState(false);useEffect(()=>{document.body.style.overflow=open?'hidden':'';return()=>{document.body.style.overflow=''}},[open]);const choose=(url:string)=>{setOpen(false);go(url)};return <><header className="header"><Logo go={go}/><nav>{nav.map(([label,url])=><button className={path===url?'active':''} key={url} onClick={()=>go(url)}>{label}</button>)}</nav><button className="visit-btn" onClick={()=>go('/contact')}>Book a visit <Icon name="arrow" size={15}/></button><button className="menu menu-always" onClick={()=>setOpen(true)} aria-label="Open all pages"><Icon name="menu"/></button></header>{open&&<div className="mega-menu" role="dialog" aria-modal="true" aria-label="All pages"><button className="mega-close" onClick={()=>setOpen(false)} aria-label="Close navigation"><Icon name="close" size={37}/></button><div className="mega-links">{menuPages.map(([label,url],i)=><button key={url} onClick={()=>choose(url)}><small>{String(i+1).padStart(2,'0')}</small>{label}<Icon name="arrow" size={23}/></button>)}<button className="talk-link" onClick={()=>choose('/contact')}><small>10</small>Talk To Us<Icon name="arrow" size={23}/></button></div><aside><p>Mahogany Farms</p><span>Managed Mahogany farmland near Bengaluru.</span><span>hello@mahoganyfarms.in</span><span>+91 95421 56208</span></aside></div>}</>}
function Footer({go}:{go:(p:string)=>void}){return <footer><div><Logo go={go}/><p>Managed Mahogany farmland,<br/>grown with patience and care.</p></div><div><b>Explore</b><button onClick={()=>go('/why-farmland')}>Why Farmland</button><button onClick={()=>go('/why-mahogany')}>Why Mahogany</button><button onClick={()=>go('/projects')}>Our farms</button></div><div><b>Company</b><button onClick={()=>go('/about')}>About us</button><button onClick={()=>go('/guides')}>Farming guides</button><button onClick={()=>go('/blog')}>Blogs</button><button onClick={()=>go('/careers')}>Careers</button></div><div><b>Contact</b><button onClick={()=>go('/farm-life')}>Mahogany life</button><button onClick={()=>go('/faq')}>FAQ</button><button onClick={()=>go('/contact')}>Talk to us</button><p>+91 95421 56208</p></div><small>© 2026 Mahogany Farms. Project information is illustrative and must be independently verified.</small></footer>}
function CallBot(){return <a className="call-bot" href="tel:+919542156208" aria-label="Call Mahogany Farms at +91 95421 56208"><span><small>Talk to us</small>+91 95421 56208</span><i><Icon name="call" size={25}/></i></a>}
function Title({eyebrow,children,body}:{eyebrow:string,children:ReactNode,body?:string}){return <div className="title"><p className="eyebrow">{eyebrow}</p><h2>{children}</h2>{body&&<p>{body}</p>}</div>}

function Home({go}:{go:(p:string)=>void}){const [story,setStory]=useState(0);const stories=[['Owning Mahogany land gave us a place our daughter can grow up with—not just an entry in a portfolio.','Rohit & Neha'],['The team explains every stage clearly and the photo updates make the farm feel close even from the city.','Arun Kumar'],['Every visit reminds us why we chose something patient, green and built for the long view.','Sneha Reddy']];return <>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">MANAGED MAHOGANY FARMLAND</p><h1>Every legacy<br/>begins with<br/><em>a seed.</em></h1><p>Own managed farmland where Mahogany is planted with care, nurtured by specialists and grown for generations.</p><div><button className="primary" onClick={()=>go('/projects')}>Explore our farms <Icon name="arrow" size={16}/></button><button className="ghost" onClick={()=>go('/contact')}>Book a farm visit</button></div></div><aside>{features.map(([icon,title])=><span key={title}><Icon name={icon}/>{title}</span>)}</aside><button className="scroll" onClick={()=>document.querySelector('.features')?.scrollIntoView({behavior:'smooth'})}>↓ &nbsp; Scroll to grow</button></section>
  <section className="section features reveal"><Title eyebrow="MANAGED FARMLAND" body="Mahogany Farms brings land ownership and focused plantation care together in one transparent experience.">We make ownership<br/><em>simple & fulfilling.</em></Title><div className="feature-grid">{features.map(([icon,title,text])=><article key={title}><Icon name={icon}/><h3>{title}</h3><p>{text}</p><button onClick={()=>go('/why-mahogany')}>Learn more <Icon name="arrow" size={13}/></button></article>)}</div></section>
  <section className="section mahogany-services reveal"><Title eyebrow="MAHOGANY FARM SERVICES" body="Four connected services support the plantation from the first prepared plot to every progress update that follows.">Your Mahogany farm,<br/><em>professionally cared for.</em></Title><div>{[
    ['/images/service-planting.png','Plantation planning','Site preparation, sapling selection and careful establishment in the field.'],
    ['/images/service-irrigation.png','Irrigation management','Planned water distribution and regular checks through changing seasons.'],
    ['/images/service-tree-care.png','Tree-health observation','On-ground inspection, maintenance notes and care appropriate to each stage.'],
    ['/images/service-reporting.png','Progress reporting','Scheduled photographs and field updates that keep owners connected.']
  ].map(([image,title,text],i)=><article key={title}><div><img src={image} alt={`${title} for a Mahogany plantation`}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p><button onClick={()=>go('/how-it-works')}>Explore service <Icon name="arrow" size={14}/></button></article>)}</div></section>
  <section className="impact reveal"><div><p className="eyebrow">A GROWING IMPACT</p><h2>Rooted in patience.<br/>Measured in care.</h2></div>{[['40K+','Mahogany saplings'],['120+','Acres managed'],['350+','Growing families'],['100%','Mahogany focused']].map(([n,l])=><span key={l}><b>{n}</b><small>{l}</small></span>)}</section>
  <section className="section life reveal"><div><p className="eyebrow">LIFE AT THE FARM</p><h2>More than a farm.<br/>It’s a <em>lifestyle.</em></h2><p>Slow walks, open skies and real time with family—your land becomes a place to return to through every season.</p><button className="primary" onClick={()=>go('/farm-life')}>Discover farm life <Icon name="arrow" size={16}/></button></div><div className="collage"><img className="big" src="/images/legacy-farm.png" alt="Family walking through a Mahogany farm"/><img src="/images/page-contact.png" alt="Pavilion at the farm"/><img src="/images/page-faq.png" alt="Farm specialist inspecting leaves"/></div></section>
  <section className="section farms reveal"><Title eyebrow="OUR FARMS">Handpicked land<br/><em>for your legacy.</em></Title><div className="farm-grid">{projects.map(p=><article key={p.name}><div><img src={p.image} alt={p.name}/><i>{p.tag}</i></div><section><h3>{p.name}</h3><p>{p.place}</p><span><small><Icon name="leaf" size={15}/>{p.acres}</small><small><Icon name="map" size={15}/>{p.size}</small></span><button onClick={()=>go('/contact')}>View project <Icon name="arrow" size={15}/></button></section></article>)}</div><button className="text-btn" onClick={()=>go('/projects')}>View all projects <Icon name="arrow" size={15}/></button></section>
  <section className="technology reveal"><div className="phone"><header>9:41 <span>● ●</span></header><h4><Icon name="leaf"/> MyFarm</h4><small>FARM OVERVIEW</small><h3>Your Mahogany plot</h3>{[['Tree health','Excellent'],['Irrigation','Complete'],['Last report','2 days ago'],['Next update','Friday']].map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}<img src="/images/sprout.png" alt="Latest farm update"/></div><div><p className="eyebrow">MYFARM TECHNOLOGY</p><h2>Your farm.<br/>Always with you.</h2><p>Follow plantation updates, irrigation status, tree-care reports and new photographs from wherever you are.</p><section>{[['chart','Growth updates'],['drop','Water status'],['camera','Photo reports'],['support','Farm support']].map(([i,t])=><span key={t}><Icon name={i as IconName}/>{t}</span>)}</section><button className="outline" onClick={()=>go('/how-it-works')}>See how we manage <Icon name="arrow" size={15}/></button></div></section>
  <section className="section testimonials reveal"><Title eyebrow="CO-FARMER STORIES">Stories from our<br/><em>growing community.</em></Title><div className="story"><button onClick={()=>setStory((story+2)%3)}>←</button><article><i>“</i><p>{stories[story][0]}</p><b>{stories[story][1]}</b><small>Mahogany co-farmer</small></article><button onClick={()=>setStory((story+1)%3)}>→</button></div><div className="dots">{stories.map((_,i)=><button key={i} className={story===i?'active':''} onClick={()=>setStory(i)}/>)}</div></section>
  <section className="cta reveal"><div><p className="eyebrow">YOUR NEXT STEP</p><h2>Ready to grow your<br/><em>Mahogany legacy?</em></h2></div><span><button onClick={()=>go('/contact')}><Icon name="map"/>Visit a farm<small>Experience it personally</small></button><button onClick={()=>go('/contact')}><Icon name="support"/>Talk to our team<small>Get all your answers</small></button><button className="primary" onClick={()=>go('/contact')}>Book a site visit</button></span></section>
  </>}

const pageData:Record<string,{k:string,title:ReactNode,body:string,image?:string}>={
  '/why-mahogany':{k:'WHY MAHOGANY',title:<>A tree chosen for<br/><em>the long view.</em></>,body:'Strong, beautiful and patient by nature—Mahogany gives your land a purpose that can span generations.',image:'/images/page-why-mahogany.png'},
  '/how-it-works':{k:'HOW IT WORKS',title:<>Land ownership,<br/><em>made considered.</em></>,body:'From your first visit to ongoing plantation care, every stage is designed to be clear and professionally managed.',image:'/images/page-how-it-works.png'},
  '/projects':{k:'OUR FARMS',title:<>Find your piece<br/>of <em>growing land.</em></>,body:'Explore managed Mahogany farmland selected for connectivity, water planning and focused long-term care.',image:'/images/page-projects.png'},
  '/farm-life':{k:'FARM LIFE',title:<>Room to breathe.<br/>Time to <em>belong.</em></>,body:'A Mahogany farm is a place to return to—quiet walks, open skies and a landscape that changes with your family.',image:'/images/page-farm-life.png'}
}
function PageHero({path}:{path:string}){const data=pageData[path];return <section className="page-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(7,24,11,.9),rgba(7,24,11,.2)),url(${data.image})`}}><div><p className="eyebrow">{data.k}</p><h1>{data.title}</h1><p>{data.body}</p></div></section>}
function PageCTA({go,title='See the land for yourself.'}:{go:(p:string)=>void,title?:string}){return <section className="mini-cta reveal"><h2>{title}</h2><button className="primary" onClick={()=>go('/contact')}>Book a farm visit <Icon name="arrow" size={16}/></button></section>}

function WhyPage({go}:{go:(p:string)=>void}){return <><PageHero path="/why-mahogany"/>
  <section className="section split reveal"><div><Title eyebrow="THE MAHOGANY DIFFERENCE">More than a plantation.<br/><em>A living legacy.</em></Title><p>Mahogany is a renowned tropical hardwood tree with a tall, straight form and broad green crown. Its story begins with suitable land, careful planting and years of professional attention.</p><p>Our model is intentionally focused: one principal tree species, a long management horizon and a team accountable for the plantation through every season.</p></div><img src="/images/seedling-close.png" alt="Healthy young Mahogany leaves"/></section>
  <section className="section matter-grid reveal"><Title eyebrow="WHY FAMILIES CHOOSE IT">A considered choice<br/><em>for patient owners.</em></Title><div>{[['01','Purposeful land use','A focused plantation plan gives every plot a clear long-term purpose.'],['02','Tangible ownership','Land can be visited, understood and experienced with your family.'],['03','Professional attention','Soil, water, tree health and maintenance are monitored by an on-ground team.'],['04','Generational thinking','Mahogany encourages decisions measured in years, not weeks.']].map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="dark-matter reveal"><div><p className="eyebrow">THE GROWTH JOURNEY</p><h2>Care changes<br/>as the tree grows.</h2><p>A sapling’s needs are different from an established tree. Management plans evolve with age, climate and site conditions.</p></div><div className="growth-list">{[['Year 01','Establishment','Soil preparation, planting, irrigation and early protection.'],['Years 02–05','Structure','Tree-health observation, formative care and weed management.'],['Years 06+','Canopy','Ongoing monitoring, pruning strategy and plantation maintenance.']].map(([a,b,c])=><article key={a}><small>{a}</small><h3>{b}</h3><p>{c}</p></article>)}</div></section>
  <section className="section due reveal"><div><Title eyebrow="A RESPONSIBLE NOTE">What Mahogany ownership<br/><em>does not promise.</em></Title></div><div>{['No guaranteed timber price','No fixed harvest date','No guaranteed land appreciation','No substitute for legal due diligence'].map(x=><span key={x}><Icon name="check" size={17}/>{x}</span>)}</div></section><PageCTA go={go}/></>}

function ProcessPage({go}:{go:(p:string)=>void}){const steps=[['01','Discover and visit','Speak with the team, review current availability and walk the farm before deciding.'],['02','Understand the land','Study access, water planning, surveys, title history and the plantation concept.'],['03','Choose your plot','Compare plot sizes, orientation and location within the larger farm community.'],['04','Complete due diligence','Use independent legal and financial advisers to review every relevant document.'],['05','Register ownership','Complete the applicable agreement, sale and registration process.'],['06','Begin the plantation','The farm team prepares the plot, irrigation and Mahogany planting plan.'],['07','Stay connected','Receive scheduled reports, tree-care notes, photos and guided visit support.']];return <><PageHero path="/how-it-works"/>
  <section className="section process-intro reveal"><Title eyebrow="A CLEAR PATH">From first conversation<br/><em>to growing land.</em></Title><p>Managed farmland should never feel mysterious. Each stage needs clear documents, named responsibilities and enough time for you to make an informed decision.</p></section>
  <section className="section timeline reveal">{steps.map(([n,t,d])=><article key={n}><b>{n}</b><div><h3>{t}</h3><p>{d}</p></div></article>)}</section>
  <section className="dark-matter reveal"><div><p className="eyebrow">THE TEAM BEHIND YOUR FARM</p><h2>Land that comes<br/>with attention.</h2><p>Exact services vary by project and should be confirmed in writing.</p></div><div className="service-grid">{[['shield','Legal coordination'],['sprout','Plantation planning'],['drop','Irrigation care'],['camera','Progress reporting'],['map','On-ground security'],['support','Owner support']].map(([i,t])=><span key={t}><Icon name={i as IconName}/>{t}</span>)}</div></section>
  <section className="section due reveal"><div><Title eyebrow="BEFORE YOU COMMIT">Documents worth<br/><em>understanding.</em></Title></div><div>{['Title and ownership structure','Survey and plot boundaries','Access-road provisions','Water and irrigation plan','Management agreement','Current regulatory requirements'].map(x=><span key={x}><Icon name="check" size={17}/>{x}</span>)}</div></section><PageCTA go={go} title="Begin with a guided farm visit."/></>}

function ProjectsPage({go}:{go:(p:string)=>void}){return <><PageHero path="/projects"/>
  <section className="section process-intro reveal"><Title eyebrow="CURRENT OPPORTUNITIES">Three settings.<br/><em>One Mahogany focus.</em></Title><p>Each farm has its own landscape, plot plan and stage of development. Visit more than one before choosing the land that feels right for your family.</p></section>
  <section className="section project-list reveal">{projects.map((p,i)=><article key={p.name}><b>0{i+1}</b><div><h2>{p.name}</h2><p>{p.place} · {p.acres} · {p.size} · {p.tag}</p></div><button onClick={()=>go('/contact')}>Request details <Icon name="arrow" size={16}/></button></article>)}</section>
  <section className="section matter-grid reveal"><Title eyebrow="HOW WE SELECT LAND">The ground matters<br/><em>before the tree begins.</em></Title><div>{[['01','Connectivity','Practical access from the city and dependable approach roads.'],['02','Water planning','A credible irrigation strategy suited to the plantation scale.'],['03','Soil suitability','Assessment of site conditions before final plantation design.'],['04','Farm experience','Room for visits, community and long-term liveability.']].map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="project-disclaimer reveal"><Icon name="shield" size={28}/><div><h3>Verify every project detail.</h3><p>Names, availability, plot sizes and acreage shown on this prototype are illustrative. Publish only verified business information and current legal documentation.</p></div></section><PageCTA go={go} title="Find the farm that fits your long view."/></>}

function FarmLifePage({go}:{go:(p:string)=>void}){return <><PageHero path="/farm-life"/>
  <section className="section split reverse reveal"><img src="/images/germination.png" alt="Fresh Mahogany growth at the farm"/><div><Title eyebrow="A DIFFERENT RHYTHM">Weekends that feel<br/><em>well spent.</em></Title><p>Walk between trees, learn how the plantation is cared for and meet people who chose the same slower, greener rhythm.</p><p>The farm is not positioned as a resort. Its real attraction is simpler: land, changing seasons and time that does not need to be rushed.</p></div></section>
  <section className="section matter-grid reveal"><Title eyebrow="WHAT THE FARM GIVES BACK">More ways to feel<br/><em>present.</em></Title><div>{[['01','Legacy','A landscape that becomes part of your family’s shared memory.'],['02','Balance','Open space and a slower rhythm beyond the city.'],['03','Learning','A chance for children to understand soil, trees and seasons.'],['04','Community','Conversations with people who value long-term stewardship.']].map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="day-band reveal"><p className="eyebrow">A DAY AT THE FARM</p>{[['08:30','Arrive and meet the team'],['09:30','Walk your plot'],['11:00','Plantation update'],['12:30','Lunch under the trees'],['15:00','Slow time with family']].map(([time,label])=><span key={time}><b>{time}</b>{label}</span>)}</section>
  <section className="community-quote reveal"><i>“</i><p>The most valuable part of the farm is not a number. It is having somewhere meaningful to return to.</p><small>— A Mahogany co-farmer</small></section><PageCTA go={go} title="Come experience a slower day."/></>}

function FAQPage({go}:{go:(p:string)=>void}){return <><section className="plain-hero"><p className="eyebrow">QUESTIONS, ANSWERED</p><h1>Clear questions.<br/><em>Honest answers.</em></h1><p>Understand the ownership, management model and long-term nature of Mahogany before making a decision.</p></section>
  <section className="section faq-layout reveal"><aside><p className="eyebrow">BEFORE YOU BUY</p><h2>Start with what<br/>matters most.</h2><p>Ask for written, project-specific answers. General website information should never replace legal documents.</p></aside><div className="faq-list">{faqs.concat([['Who manages the plantation?','A dedicated on-ground team coordinates planting, irrigation, maintenance, security and scheduled reporting. Confirm the exact service scope in the management agreement.'],['Can I sell the land later?','Resale depends on the ownership structure, market conditions and applicable law. Ask for current project-specific guidance and independent advice.'],['How often will I receive updates?','Reporting frequency varies by project. Confirm what reports, photographs and visit support are included before purchase.']]).map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="section due reveal"><div><Title eyebrow="YOUR DUE-DILIGENCE LIST">Take these questions<br/><em>to every meeting.</em></Title></div><div>{['Who legally owns the land today?','What exactly will be registered?','Which Mahogany species is planned?','What services are contractually included?','What are the recurring charges?','Which outcomes are not guaranteed?'].map(x=><span key={x}><Icon name="check" size={17}/>{x}</span>)}</div></section><PageCTA go={go} title="Still have a question? Ask us directly."/></>}

function TextHero({kicker,title,body,tone='forest'}:{kicker:string,title:ReactNode,body:string,tone?:string}){return <section className={`plain-hero editorial-hero ${tone}`}><p className="eyebrow">{kicker}</p><h1>{title}</h1><p>{body}</p></section>}

function AboutPage({go}:{go:(p:string)=>void}){return <><TextHero kicker="ABOUT MAHOGANY FARMS" title={<>We grow more than trees.<br/><em>We grow conviction.</em></>} body="A focused managed-farmland company created around one enduring tree, responsible ownership and patient land stewardship."/>
  <section className="section about-story reveal"><div><Title eyebrow="OUR BEGINNING">A simple idea,<br/><em>given deep roots.</em></Title><p>Mahogany Farms began with a clear question: can busy families own purposeful land without pretending that responsible plantation care is effortless?</p><p>Our answer is a focused model that brings together land guidance, Mahogany plantation planning, on-ground management and transparent owner communication.</p></div><div className="about-number"><b>01</b><p>Principal species</p><strong>Mahogany</strong><small>A deliberately focused plantation approach.</small></div></section>
  <section className="dark-matter reveal"><div><p className="eyebrow">WHAT WE BELIEVE</p><h2>Long-term work<br/>deserves clarity.</h2><p>Land and trees ask for patience. Owners deserve honest information while they wait.</p></div><div className="belief-list">{[['Clarity before commitment','Documents, responsibilities and limitations should be understood before purchase.'],['Care after registration','The relationship continues through plantation management and reporting.'],['Land before marketing','Site fundamentals matter more than promises or presentation.'],['No guaranteed outcomes','Growth, value and market conditions remain uncertain.']].map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="section team-section reveal"><Title eyebrow="THE TEAM">Different disciplines.<br/><em>One growing landscape.</em></Title><div>{[['Land & legal','Coordinates project documentation and ownership processes.'],['Plantation science','Plans establishment, irrigation and ongoing tree care.'],['Farm operations','Looks after maintenance, access, security and field work.'],['Owner experience','Supports visits, questions and progress communication.']].map(([t,d],i)=><article key={t}><b>0{i+1}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section><PageCTA go={go} title="Meet the people behind the farm."/></>}

function WhyFarmlandPage({go}:{go:(p:string)=>void}){return <><TextHero kicker="FARMLAND, EXPLAINED" title={<>Land is not a shortcut.<br/><em>It is a responsibility.</em></>} body="A practical guide to understanding managed farmland, asking better questions and deciding whether this kind of ownership suits you." tone="earth"/>
  <section className="section process-intro reveal"><Title eyebrow="WHY FARMLAND">A place you can<br/><em>walk, learn and steward.</em></Title><p>Farmland connects ownership with a real landscape. Its value is not limited to a future price—it can also offer family time, ecological purpose and a more direct relationship with the ground you own.</p></section>
  <section className="section matter-grid reveal"><Title eyebrow="A BALANCED VIEW">What ownership can offer.</Title><div>{[['01','Tangibility','A physical place with boundaries, access and living systems.'],['02','Purpose','Land can support a planned, professionally managed plantation.'],['03','Learning','Every season teaches something about water, soil and trees.'],['04','Legacy','A long-held landscape can become part of family memory.']].map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="section compare reveal"><div><p className="eyebrow">MANAGED FARMLAND MEANS</p><h2>You own the land.<br/>A team manages the work.</h2></div><div>{[['Ownership','Defined through project-specific legal documents.'],['Plantation','Planned and maintained by the farm operations team.'],['Communication','Progress shared through reports, photographs and visits.'],['Responsibility','Terms, fees and limitations must be understood in writing.']].map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></section><PageCTA go={go} title="Decide only after walking the land."/></>}

const guideArticles=[['Beginner','What managed farmland actually means','Ownership, management and the questions that separate the two.'],['Legal','A farmland document checklist','Documents to request and topics to review with an independent lawyer.'],['Plantation','How a Mahogany sapling establishes','The early role of soil, irrigation, protection and observation.'],['Water','Understanding a farm irrigation plan','How sources, storage and distribution support plantation care.'],['Visits','What to inspect during a farm tour','A practical list covering access, boundaries, water and field conditions.'],['Long view','Why tree growth cannot be rushed','Climate, site conditions and care make every plantation different.']]
function GuidesPage({go}:{go:(p:string)=>void}){return <><TextHero kicker="FARMING GUIDES" title={<>Learn the land<br/><em>before you own it.</em></>} body="Practical, plain-language guides about managed farmland, Mahogany plantations, documents and responsible ownership." tone="sage"/>
  <section className="section resource-grid reveal">{guideArticles.map(([tag,t,d],i)=><article key={t}><small>{tag} · 0{i+1}</small><h2>{t}</h2><p>{d}</p><button onClick={()=>go('/contact')}>Ask about this guide <Icon name="arrow" size={15}/></button></article>)}</section>
  <section className="newsletter reveal"><div><p className="eyebrow">FIELD NOTES</p><h2>One useful guide,<br/>once a month.</h2></div><form onSubmit={e=>e.preventDefault()}><input type="email" required placeholder="Your email address"/><button className="primary">Subscribe</button></form></section></>}

const posts=[
  {slug:'first-rains-after-planting',tag:'Field Journal',title:'The first rains after planting',summary:'What the farm team watches when a young plantation meets the monsoon.',body:['The first rain changes the farm quickly. Dry red soil darkens, new weeds appear and young Mahogany leaves respond to the cooler air. For the field team, this is not simply a beautiful moment—it is an important observation period.','Water must reach the root zone without remaining trapped around a young stem. The team checks drainage, soil settlement and whether every sapling remains upright after wind and heavy showers.','Rain does not remove the need for irrigation planning. A responsible schedule responds to actual soil moisture and local conditions rather than following the calendar blindly.']},
  {slug:'understanding-mahogany-leaves',tag:'Tree Notes',title:'Looking closely at Mahogany leaves',summary:'How observation helps identify stress before it becomes a larger problem.',body:['Leaves are one of the farm team’s most visible sources of information. Colour, shape, new flush and unexpected damage can all suggest that a tree deserves closer attention.','One unusual leaf does not define a plantation problem. Teams look for patterns across rows, compare trees of a similar age and consider recent rain, heat and maintenance activity.','Good observation is consistent and documented. Photographs and field notes help the team compare what they see today with earlier visits.']},
  {slug:'family-chose-the-long-view',tag:'Owner Stories',title:'Why one family chose the long view',summary:'A conversation about land, patience and creating a place to return to.',body:['The family did not begin with a spreadsheet. They began with a simple wish: to own a place their child could remember and understand.','They visited more than once, asked about ownership documents and spent time learning what plantation management actually included. The slower process helped them separate emotion from evidence.','Their Mahogany plot is still young. That is precisely what they value—the chance to watch a landscape develop alongside their family.']},
  {slug:'irrigation-is-a-system',tag:'Farm Practice',title:'Irrigation is more than a pipe',summary:'Sources, storage, scheduling and monitoring work as one system.',body:['A visible drip line is only the final part of an irrigation system. Water sources, storage, filtration, pressure and field distribution must work together.','Young trees need reliable establishment support, but excessive watering can be as unhelpful as too little. Scheduling must respond to soil, weather and plantation stage.','Before choosing managed farmland, owners should ask how water is sourced, stored, measured and maintained—not merely whether irrigation exists.']},
  {slug:'questions-before-site-visit',tag:'Due Diligence',title:'Five questions to ask before a site visit',summary:'Start with ownership, access, water, management scope and recurring costs.',body:['Ask who owns the land today and what exact interest will be transferred to you. Request documents early enough to review them independently.','Ask how access is legally provided, where the plot boundaries come from and which shared areas or services are included.','Finally, ask what the management agreement covers, what it excludes, how charges may change and which outcomes are explicitly not guaranteed.']},
  {slug:'quiet-saturday-between-trees',tag:'Farm Life',title:'A quiet Saturday between the trees',summary:'The small moments that make a landscape personally meaningful.',body:['A farm visit does not need a packed itinerary. Some of its best moments happen while walking slowly, noticing new growth and listening to the field team explain what changed.','Children ask direct questions about insects, soil and water. Adults often discover that the quiet itself is useful.','The plantation is not a resort backdrop. It is a working landscape, and respecting that work makes time at the farm more meaningful.']}
]
function BlogPage({go}:{go:(p:string)=>void}){return <><TextHero kicker="THE MAHOGANY JOURNAL" title={<>Stories from the soil.<br/><em>Notes for the long view.</em></>} body="Plantation updates, practical ownership guidance and slower stories from life between the trees." tone="ink"/>
  <section className="section blog-grid reveal">{posts.map((post,i)=><article key={post.slug}><small>{post.tag} · 0{i+1}</small><h2>{post.title}</h2><p>{post.summary}</p><button onClick={()=>go(`/blog/${post.slug}`)}>Read story <Icon name="arrow" size={14}/></button></article>)}</section>
  <section className="community-quote reveal"><i>“</i><p>Trees speak in seasons. Our journal is where we stop long enough to listen.</p><small>— Mahogany Farms field journal</small></section></>}
function BlogArticle({slug,go}:{slug:string,go:(p:string)=>void}){const post=posts.find(p=>p.slug===slug);if(!post)return <BlogPage go={go}/>;return <><section className="article-hero"><button onClick={()=>go('/blog')}>← Back to all stories</button><p className="eyebrow">{post.tag}</p><h1>{post.title}</h1><p>{post.summary}</p></section><article className="article-body reveal">{post.body.map(paragraph=><p key={paragraph}>{paragraph}</p>)}<aside><h3>Keep the long view.</h3><p>This journal shares general educational information. Confirm project-specific plantation, legal and financial details independently.</p></aside><button onClick={()=>go('/blog')}>Explore more stories <Icon name="arrow" size={15}/></button></article></>}

function CareersPage({go}:{go:(p:string)=>void}){const roles=[['Farm Operations Coordinator','Bengaluru / Field based','Coordinate visits, schedules and communication between the farm and owners.'],['Plantation Supervisor','Project location','Support daily field work, irrigation checks and plantation records.'],['Owner Experience Executive','Bengaluru','Help families understand visits, updates and project processes.']];return <><TextHero kicker="CAREERS" title={<>Do work that<br/><em>grows slowly.</em></>} body="Join a team combining land, plantation care, communication and patient long-term thinking." tone="career"/>
  <section className="section culture reveal"><Title eyebrow="WORK WITH PURPOSE">The farm needs<br/><em>many kinds of minds.</em></Title><p>We value people who communicate clearly, respect field knowledge and understand that lasting work is built through consistent attention.</p><div>{['Field-first thinking','Honest communication','Careful documentation','Respect for land and people'].map(x=><span key={x}><Icon name="check" size={17}/>{x}</span>)}</div></section>
  <section className="section role-list reveal"><p className="eyebrow">OPEN ROLES</p>{roles.map(([t,l,d])=><article key={t}><div><h2>{t}</h2><small>{l}</small></div><p>{d}</p><button onClick={()=>go('/contact')}>Apply now <Icon name="arrow" size={15}/></button></article>)}</section></>}

function Interior({path,go}:{path:string,go:(p:string)=>void}){if(path.startsWith('/blog/'))return <BlogArticle slug={path.slice(6)} go={go}/>;if(path==='/about')return <AboutPage go={go}/>;if(path==='/why-farmland')return <WhyFarmlandPage go={go}/>;if(path==='/guides')return <GuidesPage go={go}/>;if(path==='/blog'||path==='/blogs')return <BlogPage go={go}/>;if(path==='/careers')return <CareersPage go={go}/>;if(path==='/why-mahogany')return <WhyPage go={go}/>;if(path==='/how-it-works')return <ProcessPage go={go}/>;if(path==='/projects')return <ProjectsPage go={go}/>;if(path==='/farm-life')return <FarmLifePage go={go}/>;if(path==='/faq')return <FAQPage go={go}/>;return <Contact/>}
function Contact(){const [sent,setSent]=useState(false);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSent(true);e.currentTarget.reset()};return <><section className="plain-hero contact"><p className="eyebrow">BOOK A FARM VISIT</p><h1>Walk the land.<br/><em>Meet the team.</em></h1><p>Tell us when you would like to visit. We’ll help plan a thoughtful, no-pressure tour.</p></section>
  <section className="section contact-grid reveal"><div><Title eyebrow="GET IN TOUCH">Your Mahogany journey<br/>starts on the land.</Title><p>Visit the farm to understand the location, plantation design, management model and documentation.</p><div className="contact-points"><span><Icon name="phone"/><b>Call us</b><small>+91 95421 56208</small></span><span><Icon name="map"/><b>Meet us</b><small>Bengaluru, Karnataka</small></span><span><Icon name="support"/><b>Write to us</b><small>hello@mahoganyfarms.in</small></span></div></div><form onSubmit={submit}><label>Full name<input required name="name"/></label><label>Phone number<input required name="phone"/></label><label>Email<input type="email" name="email"/></label><label>Preferred date<input type="date" name="date"/></label><label className="wide">Interested farm<select><option>Choose a farm</option><option>Aranya Mahogany</option><option>Nisarga Woods</option><option>Vana Legacy</option></select></label><label className="wide">Message<textarea rows={4}/></label><button className="primary">Request a visit</button>{sent&&<p className="success">✓ Thank you. We’ll contact you shortly.</p>}</form></section>
  <section className="section matter-grid reveal"><Title eyebrow="WHAT TO EXPECT">A useful visit,<br/><em>not a sales rush.</em></Title><div>{[['01','Walk the land','See access, topography, current plantation work and plot orientation.'],['02','Meet the team','Speak with people responsible for land, plantation and owner support.'],['03','Review the model','Understand ownership, management scope, charges and reporting.'],['04','Take your time','Carry documents away and review them independently before deciding.']].map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="visit-note reveal"><div><p className="eyebrow">VISIT PREPARED</p><h2>Bring your questions.<br/>Wear comfortable shoes.</h2></div><p>Farm visits typically involve walking on uneven ground. Carry water, sun protection and a list of every legal, financial and plantation question you want answered.</p></section></>}

export default function App(){const [path,setPath]=useState(()=>location.pathname.replace(/\/$/,'')||'/');const go=(p:string)=>{history.pushState({},'',p);setPath(p);scrollTo({top:0,behavior:'smooth'})};useEffect(()=>{const pop=()=>setPath(location.pathname.replace(/\/$/,'')||'/');addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[]);useEffect(()=>{const els=document.querySelectorAll('.reveal');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});els.forEach(e=>io.observe(e));return()=>io.disconnect()},[path]);return <main><Header go={go} path={path}/>{path==='/'?<Home go={go}/>:<Interior path={path} go={go}/>}<Footer go={go}/><CallBot/></main>}
